#!/bin/bash

IMAGE_NAME=${PWD##*/}
VCS_REF=`git rev-parse --short HEAD`
BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`
VERSION="1.0"

docker build \
  --build-arg VCS_REF="$VCS_REF" \
  --build-arg BUILD_DATE="$BUILD_DATE" \
  --build-arg VERSION="$VERSION" \
  --tag "flow123d/$IMAGE_NAME" .
